### ISSUE TITLE
Add optional count input for measurements of 100 or 1K kernel weight

### ISSUE THREAD

**Issue by bellerbrock** [PhenoApps/Inventory#4]
It would be helpful when a seedlot is first used to be able to record both the weight and the count of the first deduction of seed. The two measurements could then be used to calculate 100 or 1K kernel weight.

For breedbase users the 100 or 1K kernel weight could then be stored as a property of the seedlot, and later help determine how many seeds have been used or are still available after further weight-based seedlot transactions.

**Comment by trife** [comment]
We're in the early planning stages of a new Inventory app that can functionally manage inventory. I'll make sure to include count as a parameter that should be included.
