### ISSUE TITLE
Building fails - external java library forbidden

### ISSUE THREAD

**Issue by StephenSzwiec** [PhenoApps/Inventory#7]
Downloading `https://dl.bintray.com/pheno-apps/pheno-apps-java-client-library/org/phenoapps/javalib/1.0.2/javalib-1.0.2.pom` to build this app fails with "`Forbidden`" from server.

**Comment by trife** [comment]
Bintray shut down operations in May- we've replaced that library with the GitHub packages library (see other apps).

We're currently evaluating our need for an updated inventory app with more features and may update this app or integrate those features into a new app altogether.

**Comment by StephenSzwiec** [comment]
Thank you for your explanation. At the present time, I am attempting to build this software to study how it works: specifically the SQL DB store for android in an emulated environment. 

Would you have working build instructions for the required library dependencies? I have toyed around with the `JavaLibraryBuilder`, but building this fails for lack of a `secrets.properties` file. Thank you for your time with this matter.
